import uuid
from datetime import datetime
from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, JSON, ForeignKey, Text
from sqlalchemy.orm import relationship
from app.db.database import Base

def generate_uuid():
    return str(uuid.uuid4())

class Profile(Base):
    __tablename__ = "profiles"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    email = Column(String(255), unique=True, index=True, nullable=False)
    full_name = Column(String(255), nullable=False)
    role = Column(String(50), default="analyst")  # user, analyst, administrator, border_officer
    domain = Column(String(50), default="airport_security")  # airport_security, airline, immigration, border_travel
    organization = Column(String(255), default="DocShield Security Command")
    avatar_url = Column(String(512), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    screenings = relationship("ScreeningSession", back_populates="user")
    notifications = relationship("Notification", back_populates="user", cascade="all, delete-orphan")
    audit_logs = relationship("AuditLog", back_populates="user")

class ScreeningSession(Base):
    """
    Central Screening Session Model.
    Primary key: id (UUID generated by backend for session data isolation).
    person_name: Operator-provided screening reference (NOT a unique identity key).
    """
    __tablename__ = "screening_sessions"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    person_name = Column(String(255), nullable=False, default="Screening Subject")
    user_id = Column(String(36), ForeignKey("profiles.id"), nullable=True)
    domain = Column(String(50), nullable=False)  # airport_security, airline, immigration, border_travel
    document_type = Column(String(50), nullable=False)  # passport, visa, national_id, driving_license, residence_permit, travel_permit, boarding_pass, compare_documents, face_verification
    travel_reference = Column(JSON, nullable=True)  # { "ticket_number": "...", "pnr": "..." }
    status = Column(String(50), default="created")  # created, queued, processing, completed, failed
    stage = Column(String(50), default="pending")  # quality, classification, ocr, mrz, validation, tampering, face, consistency, risk, completed
    risk_score = Column(Float, default=0.0)  # 0 to 100
    risk_level = Column(String(50), default="UNABLE_TO_DETERMINE")  # LOW_RISK, REVIEW_RECOMMENDED, HIGH_RISK, UNABLE_TO_DETERMINE
    manual_review_required = Column(Boolean, default=False)
    is_demo = Column(Boolean, default=False)
    quality_result = Column(JSON, nullable=True)
    classification_result = Column(JSON, nullable=True)
    consistency_result = Column(JSON, nullable=True)
    individual_analyses = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    user = relationship("Profile", back_populates="screenings")
    documents = relationship("UploadedDocument", back_populates="screening", cascade="all, delete-orphan")
    ocr_result = relationship("OCRResult", back_populates="screening", uselist=False, cascade="all, delete-orphan")
    mrz_result = relationship("MRZResult", back_populates="screening", uselist=False, cascade="all, delete-orphan")
    validation_results = relationship("ValidationResult", back_populates="screening", cascade="all, delete-orphan")
    tampering_result = relationship("TamperingResult", back_populates="screening", uselist=False, cascade="all, delete-orphan")
    face_result = relationship("FaceResult", back_populates="screening", uselist=False, cascade="all, delete-orphan")
    risk_assessment = relationship("RiskAssessment", back_populates="screening", uselist=False, cascade="all, delete-orphan")
    reports = relationship("Report", back_populates="screening", cascade="all, delete-orphan")

class UploadedDocument(Base):
    __tablename__ = "uploaded_documents"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    screening_id = Column(String(36), ForeignKey("screening_sessions.id"), nullable=False)
    storage_path = Column(String(512), nullable=False)
    original_filename = Column(String(255), nullable=False)
    mime_type = Column(String(100), nullable=False)
    file_size = Column(Integer, nullable=False)
    width = Column(Integer, nullable=True)
    height = Column(Integer, nullable=True)
    doc_role = Column(String(50), default="primary_document")  # primary_document, secondary_document, live_selfie, eticket
    created_at = Column(DateTime, default=datetime.utcnow)

    screening = relationship("ScreeningSession", back_populates="documents")

class OCRResult(Base):
    __tablename__ = "ocr_results"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    screening_id = Column(String(36), ForeignKey("screening_sessions.id"), nullable=False)
    raw_text = Column(Text, nullable=True)
    structured_fields = Column(JSON, nullable=True)  # { "name": "...", "document_number": "...", ... }
    average_confidence = Column(Float, default=0.0)
    bounding_boxes = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    screening = relationship("ScreeningSession", back_populates="ocr_result")

class MRZResult(Base):
    __tablename__ = "mrz_results"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    screening_id = Column(String(36), ForeignKey("screening_sessions.id"), nullable=False)
    mrz_detected = Column(Boolean, default=False)
    mrz_text = Column(Text, nullable=True)
    document_number = Column(String(50), nullable=True)
    date_of_birth = Column(String(50), nullable=True)
    expiry_date = Column(String(50), nullable=True)
    nationality = Column(String(50), nullable=True)
    issuer = Column(String(50), nullable=True)
    sex = Column(String(10), nullable=True)
    checksums = Column(JSON, nullable=True)  # { "doc_num": true, "dob": true, "expiry": true, "composite": true }
    is_valid = Column(Boolean, default=False)
    confidence = Column(Float, default=0.0)
    field_matches = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    screening = relationship("ScreeningSession", back_populates="mrz_result")

class ValidationResult(Base):
    __tablename__ = "validation_results"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    screening_id = Column(String(36), ForeignKey("screening_sessions.id"), nullable=False)
    check_name = Column(String(100), nullable=False)
    status = Column(String(20), nullable=False)  # PASS, WARNING, FAIL, INFO
    severity = Column(String(20), default="info")  # low, medium, high, info
    message = Column(String(500), nullable=False)
    details = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    screening = relationship("ScreeningSession", back_populates="validation_results")

class TamperingResult(Base):
    __tablename__ = "tampering_results"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    screening_id = Column(String(36), ForeignKey("screening_sessions.id"), nullable=False)
    tampering_detected = Column(Boolean, default=False)
    score = Column(Float, default=0.0)  # 0.0 to 1.0 (or 0-100)
    confidence = Column(Float, default=0.0)
    status = Column(String(50), default="CLEAR")  # CLEAR, REVIEW_RECOMMENDED, HIGH_ANOMALY
    suspicious_regions = Column(JSON, nullable=True)  # list of {x, y, width, height, reason, score}
    heatmap_path = Column(String(512), nullable=True)
    heatmap_base64 = Column(Text, nullable=True)
    signals = Column(JSON, nullable=True)  # ELA, FFT, noise, compression metrics
    created_at = Column(DateTime, default=datetime.utcnow)

    screening = relationship("ScreeningSession", back_populates="tampering_result")

class FaceResult(Base):
    __tablename__ = "face_results"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    screening_id = Column(String(36), ForeignKey("screening_sessions.id"), nullable=False)
    face_detected_document = Column(Boolean, default=False)
    face_detected_live = Column(Boolean, default=False)
    face_count_document = Column(Integer, default=0)
    face_count_live = Column(Integer, default=0)
    similarity = Column(Float, default=0.0)  # 0.0 to 1.0
    status = Column(String(50), default="NOT_EVALUATED")  # MATCH_SIGNAL, LOW_MATCH_SIGNAL, MISMATCH_SIGNAL, UNABLE_TO_VERIFY, NOT_EVALUATED
    confidence = Column(Float, default=0.0)
    document_face_box = Column(JSON, nullable=True)
    live_face_box = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    screening = relationship("ScreeningSession", back_populates="face_result")

class RiskAssessment(Base):
    __tablename__ = "risk_assessments"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    screening_id = Column(String(36), ForeignKey("screening_sessions.id"), nullable=False)
    risk_score = Column(Float, default=0.0)  # 0 to 100
    risk_level = Column(String(50), nullable=False)  # LOW_RISK, REVIEW_RECOMMENDED, HIGH_RISK, UNABLE_TO_DETERMINE
    contributors = Column(JSON, nullable=True)  # list of { "title": "...", "points": +25, "severity": "high", "description": "..." }
    explanation = Column(JSON, nullable=True)  # { "summary": "...", "checks_passed": [...], "checks_failed": [...] }
    recommendation = Column(String(255), default="Standard verification sufficient")
    created_at = Column(DateTime, default=datetime.utcnow)

    screening = relationship("ScreeningSession", back_populates="risk_assessment")

class Report(Base):
    __tablename__ = "reports"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    screening_id = Column(String(36), ForeignKey("screening_sessions.id"), nullable=False)
    report_path = Column(String(512), nullable=False)
    generated_by = Column(String(255), default="DocShield AI Engine")
    created_at = Column(DateTime, default=datetime.utcnow)

    screening = relationship("ScreeningSession", back_populates="reports")

class Notification(Base):
    __tablename__ = "notifications"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    user_id = Column(String(36), ForeignKey("profiles.id"), nullable=False)
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    type = Column(String(50), default="info")  # info, high_risk, completed, warning, system
    is_read = Column(Boolean, default=False)
    link = Column(String(255), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("Profile", back_populates="notifications")

class SystemSetting(Base):
    __tablename__ = "system_settings"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    user_id = Column(String(36), ForeignKey("profiles.id"), nullable=True)
    preferences = Column(JSON, nullable=True)  # theme, language, sensitivity, retention
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class AuditLog(Base):
    __tablename__ = "audit_logs"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    user_id = Column(String(36), ForeignKey("profiles.id"), nullable=True)
    action = Column(String(100), nullable=False)
    resource_type = Column(String(50), nullable=False)
    resource_id = Column(String(50), nullable=True)
    details = Column(JSON, nullable=True)
    ip_address = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("Profile", back_populates="audit_logs")
